- name: simple condition
  hosts: localhost
  vars:
    NAME: yashwanth
  tasks: 
  - name: run this if the name is yashwanth
    ansible.builtin.debug:
      msg: "my name is {{NAME}}"
    when: NAME == "yashwanth"   