- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: "nginx" , state: "absent"}
    - {name: "postfix" , state: "present"}
    - {name: "mailx" , state: "removed"}
    - {name: "cyrus-sasl-plain" , state: "installed"}  